<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2019 rel. 3 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:altova="http://www.altova.com" xmlns:altova-xfi="http://www.altova.com/xslt-extensions/xbrl" xmlns:altovaext="http://www.altova.com/xslt-extensions" xmlns:array="http://www.w3.org/2005/xpath-functions/array" xmlns:clitype="clitype" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:iso4217="http://www.xbrl.org/2003/iso4217" xmlns:java="java" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:map="http://www.w3.org/2005/xpath-functions/map" xmlns:math="http://www.w3.org/2005/xpath-functions/math" xmlns:sps="http://www.altova.com/StyleVision/user-xpath-functions" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xff="http://www.xbrl.org/2010/function/formula" xmlns:xfi="http://www.xbrl.org/2008/function/instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" exclude-result-prefixes="altova altova-xfi altovaext array clitype fn iso4217 java link map math sps xbrldi xbrli xff xfi xlink xs xsi">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:variable name="altova:nPxPerIn" select="96"/>
	<xsl:template match="/">
		<html>
			<head>
				<title/>
				<meta name="generator" content="Altova StyleVision Enterprise Edition 2019 rel. 3 (http://www.altova.com)"/>
				<meta http-equiv="X-UA-Compatible" content="IE=9"/>
				<xsl:comment>[if IE]&gt;&lt;STYLE type=&quot;text/css&quot;&gt;.altova-rotate-left-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3)} .altova-rotate-right-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1)} &lt;/STYLE&gt;&lt;![endif]</xsl:comment>
				<xsl:comment>[if !IE]&gt;&lt;!</xsl:comment>
				<style type="text/css">.altova-rotate-left-textbox{-webkit-transform: rotate(-90deg) translate(-100%, 0%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(-90deg) translate(-100%, 0%); -moz-transform-origin: 0% 0%;-ms-transform: rotate(-90deg) translate(-100%, 0%); -ms-transform-origin: 0% 0%;}.altova-rotate-right-textbox{-webkit-transform: rotate(90deg) translate(0%, -100%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(90deg) translate(0%, -100%); -moz-transform-origin: 0% 0%;-ms-transform: rotate(90deg) translate(0%, -100%); -ms-transform-origin: 0% 0%;}</style>
				<xsl:comment>&lt;![endif]</xsl:comment>
				<style type="text/css">@page { margin-left:0.60in; margin-right:0.60in; margin-top:0.79in; margin-bottom:0.79in } @media print { br.altova-page-break { page-break-before: always; } div.altova-page-break { page-break-before: always; } }</style>
			</head>
			<body style="content:normal; font-family:Arial; font-size:medium; ">
				<xsl:for-each select="$XML">
					<br/>
					<br/>
					<span style="color:blue; font-size:24pt; font-weight:bold; ">
						<xsl:text>Journal Kommunhälsan - TEAM-FHV</xsl:text>
					</span>
					<br/>
					<br/>
					<xsl:for-each select="PATIENT">
						<span>
							<xsl:text>&#160;</xsl:text>
						</span>
						<h2 style="background-color:#E9E9EA; ">
							<span>
								<xsl:text>Patient</xsl:text>
							</span>
						</h2>
						<br/>
						<table style="border-collapse:collapse; " border="1">
							<xsl:variable name="altova:CurrContextGrid_0" select="."/>
							<tbody>
								<tr>
									<td style="background-color:#C6EFCE; width:2.50in; ">
										<span style="color:black; font-weight:bold; ">
											<xsl:text>Förnamn</xsl:text>
										</span>
										<br/>
									</td>
									<td colspan="3" style="width:6.41in; ">
										<xsl:for-each select="PAT_FIRSTNAME">
											<xsl:apply-templates/>
										</xsl:for-each>
										<span>
											<xsl:text>&#160;</xsl:text>
										</span>
									</td>
								</tr>
								<tr>
									<td style="background-color:#C6EFCE; width:2.50in; ">
										<span style="color:black; font-weight:bold; ">
											<xsl:text>Efternamn</xsl:text>
										</span>
									</td>
									<td colspan="3" style="width:6.41in; ">
										<xsl:for-each select="PAT_LASTNAME">
											<xsl:apply-templates/>
										</xsl:for-each>
									</td>
								</tr>
								<tr>
									<td style="background-color:#C6EFCE; width:2.50in; ">
										<span style="font-weight:bold; ">
											<xsl:text>Personnummer</xsl:text>
										</span>
									</td>
									<td colspan="3" style="width:6.41in; ">
										<xsl:for-each select="PAT_ID">
											<xsl:apply-templates/>
										</xsl:for-each>
									</td>
								</tr>
								<tr>
									<td style="background-color:#C6EFCE; width:2.50in; ">
										<span style="font-weight:bold; ">
											<xsl:text>Kön</xsl:text>
										</span>
									</td>
									<td colspan="3" style="width:6.41in; ">
										<xsl:for-each select="PAT_SEX">
											<xsl:apply-templates/>
										</xsl:for-each>
									</td>
								</tr>
								<tr>
									<td style="background-color:#C6EFCE; width:2.50in; ">
										<span style="font-weight:bold; ">
											<xsl:text>Registrerad i journalsystemet</xsl:text>
										</span>
									</td>
									<td colspan="3" style="margin-bottom:auto; margin-left:auto; margin-right:auto; margin-top:auto; width:6.41in; ">
										<xsl:for-each select="PAT_REGISTERED_DATE">
											<xsl:apply-templates/>
										</xsl:for-each>
									</td>
								</tr>
								<tr>
									<td style="background-color:#C6EFCE; width:2.50in; ">
										<span style="font-weight:bold; ">
											<xsl:text>Adress</xsl:text>
										</span>
									</td>
									<td colspan="3" style="width:6.41in; ">
										<xsl:for-each select="ADRESSES">
											<xsl:for-each select="HOME_ADDRESS">
												<xsl:apply-templates/>
											</xsl:for-each>
											<xsl:for-each select="SEPARATOR">
												<xsl:apply-templates/>
											</xsl:for-each>
											<xsl:for-each select="POSTAL_ADDRESS">
												<xsl:apply-templates/>
											</xsl:for-each>
										</xsl:for-each>
									</td>
								</tr>
								<tr>
									<td style="background-color:#C6EFCE; width:2.50in; ">
										<span style="font-weight:bold; ">
											<xsl:text>Telefon</xsl:text>
										</span>
									</td>
									<td style="width:6.41in; ">
										<span>
											<xsl:text>Hem: </xsl:text>
										</span>
										<xsl:for-each select="TELEPHONES">
											<xsl:for-each select="HOME_PHONE">
												<xsl:apply-templates/>
											</xsl:for-each>
										</xsl:for-each>
										<br/>
									</td>
									<td style="width:6.41in; ">
										<span>
											<xsl:text>Arbete: </xsl:text>
										</span>
										<xsl:for-each select="TELEPHONES">
											<xsl:for-each select="WORK_PHONE">
												<xsl:apply-templates/>
											</xsl:for-each>
										</xsl:for-each>
									</td>
									<td style="width:6.41in; ">
										<span>
											<xsl:text>Mobil: </xsl:text>
										</span>
										<xsl:for-each select="TELEPHONES">
											<xsl:for-each select="MOBIL_PHONE">
												<xsl:apply-templates/>
											</xsl:for-each>
										</xsl:for-each>
									</td>
								</tr>
								<tr>
									<td style="background-color:#C6EFCE; width:2.50in; ">
										<span style="font-weight:bold; ">
											<xsl:text>Yrke</xsl:text>
										</span>
									</td>
									<td colspan="3" style="width:6.41in; ">
										<xsl:for-each select="PROF_ID">
											<xsl:for-each select="PROFESSION">
												<xsl:apply-templates/>
											</xsl:for-each>
										</xsl:for-each>
									</td>
								</tr>
								<tr>
									<td style="background-color:#C6EFCE; width:2.50in; ">
										<span style="font-weight:bold; ">
											<xsl:text>Anställning</xsl:text>
										</span>
									</td>
									<td style="width:6.41in; ">
										<span>
											<xsl:text>Nummer:</xsl:text>
										</span>
										<xsl:for-each select="COMPANY">
											<xsl:for-each select="EMPLOYMENT">
												<xsl:for-each select="EMPL_NUMBER">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</td>
									<td colspan="2" style="width:6.41in; ">
										<span>
											<xsl:text>Från:</xsl:text>
										</span>
										<xsl:for-each select="COMPANY">
											<xsl:for-each select="EMPLOYMENT">
												<xsl:for-each select="EMPL_FROM_DATE">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</td>
								</tr>
								<tr>
									<td style="background-color:#C6EFCE; width:2.50in; ">
										<span style="font-weight:bold; ">
											<xsl:text>Arbetsplats</xsl:text>
										</span>
									</td>
									<td colspan="3" style="width:6.41in; ">
										<xsl:for-each select="COMPANY">
											<xsl:for-each select="COMPANY_NAME">
												<xsl:apply-templates/>
											</xsl:for-each>
											<span>
												<xsl:text>&#160;</xsl:text>
											</span>
											<xsl:for-each select="COMPANY_UNIT">
												<xsl:apply-templates/>
											</xsl:for-each>
										</xsl:for-each>
									</td>
								</tr>
							</tbody>
						</table>
						<br/>
						<br/>
						<h2 style="background-color:#E9E9EA; ">
							<span>
								<xsl:text>Medicinsk basdata</xsl:text>
							</span>
						</h2>
						<table style="border-collapse:collapse; " border="1" width="100%">
							<xsl:variable name="altova:CurrContextGrid_1" select="."/>
							<tbody>
								<tr>
									<td style="background-color:#C6EFCE; width:1.93in; ">
										<span style="font-weight:bold; ">
											<xsl:text>Hereditet</xsl:text>
										</span>
									</td>
									<td>
										<xsl:for-each select="MEDBAS">
											<xsl:for-each select="HEREDITY">
												<xsl:apply-templates/>
											</xsl:for-each>
										</xsl:for-each>
									</td>
								</tr>
								<tr>
									<td style="background-color:#C6EFCE; width:1.93in; ">
										<span style="font-weight:bold; ">
											<xsl:text>Sociala förhållanden</xsl:text>
										</span>
									</td>
									<td>
										<xsl:for-each select="MEDBAS">
											<xsl:for-each select="FAMILY_SOCIAL">
												<xsl:apply-templates/>
											</xsl:for-each>
										</xsl:for-each>
									</td>
								</tr>
								<tr>
									<td style="background-color:#C6EFCE; width:1.93in; ">
										<span style="font-weight:bold; ">
											<xsl:text>Tidigare sjukdomar</xsl:text>
										</span>
									</td>
									<td>
										<xsl:for-each select="MEDBAS">
											<xsl:for-each select="PREVIOUS_ILLNESS">
												<xsl:apply-templates/>
											</xsl:for-each>
										</xsl:for-each>
									</td>
								</tr>
								<tr>
									<td style="background-color:#C6EFCE; width:1.93in; ">
										<span style="font-weight:bold; ">
											<xsl:text>Överkänslighet</xsl:text>
										</span>
									</td>
									<td>
										<xsl:for-each select="MEDBAS">
											<xsl:for-each select="SENSITIVITY">
												<xsl:apply-templates/>
											</xsl:for-each>
										</xsl:for-each>
									</td>
								</tr>
								<tr>
									<td style="background-color:#C6EFCE; width:1.93in; ">
										<span style="font-weight:bold; ">
											<xsl:text>Allergi</xsl:text>
										</span>
									</td>
									<td>
										<xsl:for-each select="MEDBAS">
											<xsl:for-each select="ALLERGY">
												<xsl:apply-templates/>
											</xsl:for-each>
										</xsl:for-each>
									</td>
								</tr>
							</tbody>
						</table>
						<br/>
						<br/>
						<h2 style="background-color:#E9E9EA; ">
							<span style="font-size:18pt; ">
								<xsl:text>Journalanteckningar</xsl:text>
							</span>
							<hr style="border-bottom-color:black; border-bottom-width:medium; "/>
						</h2>
						<xsl:for-each select="CONTACT">
							<br/>
							<xsl:for-each select="CONTACT_DATE">
								<span style="font-size:14pt; font-weight:bold; ">
									<xsl:apply-templates/>
								</span>
							</xsl:for-each>
							<span>
								<xsl:text>&#160;</xsl:text>
							</span>
							<xsl:for-each select="JO_GRUPP">
								<xsl:apply-templates/>
							</xsl:for-each>
							<hr/>
							<xsl:for-each select="NOTE">
								<xsl:for-each select="CONTTYPE_NAME">
									<span style="font-weight:bold; ">
										<xsl:apply-templates/>
									</span>
								</xsl:for-each>
								<br/>
								<xsl:for-each select="NOTE_HTML">
									<xsl:apply-templates/>
								</xsl:for-each>
								<br/>
								<xsl:for-each select="NO_DICTATION">
									<xsl:apply-templates/>
								</xsl:for-each>
								<br/>
								<xsl:for-each select="NO_DIAGNOS">
									<xsl:apply-templates/>
								</xsl:for-each>
								<br/>
								<xsl:for-each select="NO_SIGNED">
									<span style="font-style:italic; ">
										<xsl:text>Signeringsdatum: </xsl:text>
									</span>
									<span style="font-style:italic; ">
										<xsl:apply-templates/>
									</span>
								</xsl:for-each>
								<xsl:for-each select="NO_SIGNER">
									<span>
										<xsl:text>&#160;</xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
							</xsl:for-each>
							<br/>
							<br/>
							<xsl:for-each select="CORRESPONDENCE">
								<xsl:for-each select="CORR_SUBJECT">
									<span style="font-weight:bold; ">
										<xsl:apply-templates/>
									</span>
								</xsl:for-each>
								<br/>
								<xsl:for-each select="CORR_TXT">
									<xsl:apply-templates/>
								</xsl:for-each>
							</xsl:for-each>
							<xsl:for-each select="LAB_ORDER">
								<xsl:for-each select="CONTTYPE_NAME">
									<span style="font-weight:bold; ">
										<xsl:apply-templates/>
									</span>
								</xsl:for-each>
								<br/>
								<xsl:for-each select="ANALYSIS_RESULT">
									<xsl:for-each select="NAME_LONG">
										<xsl:apply-templates/>
									</xsl:for-each>
									<xsl:for-each select="RESULT_TXT">
										<xsl:apply-templates/>
									</xsl:for-each>
									<xsl:for-each select="PATHOLOGY">
										<span style="color:red; ">
											<xsl:apply-templates/>
										</span>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
							<br/>
							<xsl:for-each select="RECEPT">
								<xsl:for-each select="CONTTYPE_NAME">
									<span style="font-weight:bold; ">
										<xsl:apply-templates/>
									</span>
								</xsl:for-each>
								<br/>
								<xsl:for-each select="REC_FORM">
									<span style="background-color:#00c0ff; color:#1e1e1e; ">
										<xsl:apply-templates/>
									</span>
								</xsl:for-each>
								<xsl:for-each select="REC_DESCR">
									<span style="background-color:#00c0ff; ">
										<xsl:apply-templates/>
									</span>
								</xsl:for-each>
								<xsl:for-each select="REC_STRENGTH">
									<span style="background-color:#00c0ff; ">
										<xsl:apply-templates/>
									</span>
								</xsl:for-each>
								<xsl:for-each select="REC_QTY">
									<span style="background-color:#00c0ff; ">
										<xsl:apply-templates/>
									</span>
								</xsl:for-each>
								<xsl:for-each select="REC_USAGE">
									<span style="background-color:#00c0ff; ">
										<xsl:apply-templates/>
									</span>
								</xsl:for-each>
								<xsl:for-each select="REC_WRITER">
									<span style="font-style:italic; ">
										<xsl:apply-templates/>
									</span>
								</xsl:for-each>
							</xsl:for-each>
							<br/>
							<table style="border-collapse:collapse; " border="1">
								<xsl:variable name="altova:CurrContextGrid_2" select="."/>
								<tbody>
									<xsl:for-each select="AUDIOGRAM">
										<xsl:for-each select="AUDIOGRAM_VALUE">
											<tr>
												<td>
													<xsl:for-each select="AU_FREQENCE">
														<span style="background-color:#ffffa0; ">
															<xsl:apply-templates/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="AU_LEFT">
														<span style="color:#0046ff; ">
															<xsl:apply-templates/>
														</span>
													</xsl:for-each>
												</td>
												<td>
													<xsl:for-each select="AU_RIGHT">
														<span style="color:red; ">
															<xsl:apply-templates/>
														</span>
													</xsl:for-each>
												</td>
											</tr>
										</xsl:for-each>
									</xsl:for-each>
								</tbody>
							</table>
						</xsl:for-each>
						<br/>
						<br/>
						<br/>
						<br/>
					</xsl:for-each>
					<br/>
				</xsl:for-each>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
